// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/app/callback": {
            "get": {
                "description": "OAuth2 Callback für ESI, speichert Token und setzt Cookie",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "ESI Callback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization Code",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to home",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/app/express/mail": {
            "post": {
                "description": "Verwendet einen fest konfigurierten Service-Char (ENV), sendet Mail an eine Ziel-Corp (ENV).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mail"
                ],
                "summary": "EVE-Mail für EXPRESS senden (Service-Char -\u003e Ziel-Corp)",
                "parameters": [
                    {
                        "description": "Express Daten",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/structs.ExpressMailRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "mail_id",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/app/login": {
            "get": {
                "description": "Leitet zum ESI-Login um",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login redirect",
                "responses": {
                    "302": {
                        "description": "Redirect",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/app/logout": {
            "get": {
                "description": "Löscht den Auth-Cookie und entfernt das Token aus dem Speicher",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout",
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/app/mail": {
            "post": {
                "description": "Sendet eine EVE-Mail über ESI. Empfänger nutzt kein CSPA, daher wird ` + "`" + `approved_cost` + "`" + ` immer 0 gesendet.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mail"
                ],
                "summary": "EVE-Mail senden (ohne CSPA)",
                "parameters": [
                    {
                        "description": "Mail-Daten",
                        "name": "mail",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/structs.SendMailRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/structs.MailIDResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structs.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/structs.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/structs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/app/me": {
            "get": {
                "description": "Gibt Charakter-ID und Name zurück (aus Cookie)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "User Info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.VerifyResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/app/ping": {
            "get": {
                "description": "Gibt \"pong\" zurück",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Healthcheck",
                "responses": {
                    "200": {
                        "description": "pong",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/app/role": {
            "get": {
                "description": "Gibt die Rolle des eingeloggten Benutzers zurück",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Benutzerrolle abrufen",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "DB error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/app/routes": {
            "get": {
                "description": "Gibt alle verfügbaren Transport-Routen zurück",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Routes"
                ],
                "summary": "Get all active routes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/structs.Route"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Erstellt eine neue Transport-Route",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Routes"
                ],
                "summary": "Neue Route anlegen",
                "parameters": [
                    {
                        "description": "Neue Route",
                        "name": "route",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/structs.Route"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/structs.Route"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "DB Insert error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/app/routes/{id}": {
            "put": {
                "description": "Aktualisiert eine bestehende Transport-Route anhand der ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Routes"
                ],
                "summary": "Route aktualisieren",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Route ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Route-Daten",
                        "name": "route",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/structs.Route"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.Route"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "DB Update error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Löscht eine Transport-Route anhand der ID",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Routes"
                ],
                "summary": "Route löschen",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Route ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Deleted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "DB Delete error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/app/users": {
            "get": {
                "description": "Gibt eine Liste aller Benutzer mit deren Rollen zurück (nur Admin).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Alle Benutzer abrufen",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/structs.User"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "DB error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/app/users/{charID}/role": {
            "put": {
                "description": "Setzt die Rolle eines Benutzers anhand der charID (nur Admin).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Rolle eines Benutzers ändern",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Character ID",
                        "name": "charID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Neue Rolle",
                        "name": "role",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/structs.UpdateRoleReq"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON or role",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "DB error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "structs.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Invalid JSON"
                }
            }
        },
        "structs.ExpressMailRequest": {
            "type": "object",
            "properties": {
                "collateral_isk": {
                    "description": "0..20B",
                    "type": "integer"
                },
                "customer_char_id": {
                    "description": "optional: Wer hat ausgelöst?",
                    "type": "integer"
                },
                "customer_char_name": {
                    "type": "string"
                },
                "express": {
                    "description": "true",
                    "type": "boolean"
                },
                "notes": {
                    "description": "optional",
                    "type": "string"
                },
                "reward_isk": {
                    "description": "z.B. 826500000",
                    "type": "integer"
                },
                "route": {
                    "description": "\"Amarr ↔ K-6K16\"",
                    "type": "string"
                },
                "volume_m3": {
                    "description": "z.B. 165000",
                    "type": "integer"
                }
            }
        },
        "structs.MailIDResponse": {
            "type": "object",
            "properties": {
                "mail_id": {
                    "type": "integer",
                    "example": 399492427
                }
            }
        },
        "structs.MailRecipient": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1234546456
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "character",
                        "corporation",
                        "alliance",
                        "mailing_list"
                    ],
                    "example": "character"
                }
            }
        },
        "structs.Route": {
            "type": "object",
            "properties": {
                "allowedCorps": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "from": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "noCollateral": {
                    "type": "boolean"
                },
                "pricePerM3": {
                    "type": "number"
                },
                "to": {
                    "type": "string"
                },
                "visibility": {
                    "description": "\"all\" | \"whitelist\"",
                    "type": "string"
                }
            }
        },
        "structs.SendMailRequest": {
            "type": "object",
            "properties": {
                "autoApproveCspa": {
                    "type": "boolean",
                    "example": false
                },
                "body": {
                    "type": "string",
                    "example": "Hello World"
                },
                "recipients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/structs.MailRecipient"
                    }
                },
                "subject": {
                    "type": "string",
                    "example": "Test"
                }
            }
        },
        "structs.UpdateRoleReq": {
            "type": "object",
            "properties": {
                "role": {
                    "type": "string"
                }
            }
        },
        "structs.User": {
            "description": "Darstellung eines Users für die Admin-API.",
            "type": "object",
            "properties": {
                "char_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "structs.VerifyResponse": {
            "type": "object",
            "properties": {
                "CharacterID": {
                    "type": "integer",
                    "example": 12345678
                },
                "CharacterName": {
                    "type": "string",
                    "example": "Pilot McFly"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Speedliner API",
	Description:      "REST API für Speedliner",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
